/******************************************************************************
 * The MIT License (MIT)
 * 
 * Copyright (c) 2014 Crytek
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 ******************************************************************************/


#pragma once

// typed enum so that templates will pick up specialisations
#define GLenum RDCGLenum

#include "gl_enum.h"

#include "official/glcorearb.h"
#include "official/glext.h"

#if defined(WIN32)
#include "official/wglext.h"

struct GLWindowingData
{
	HDC DC;
	HGLRC ctx;
	HWND wnd;
};

#elif defined(LINUX)
// cheeky way to prevent GL/gl.h from being included, as we want to use
// glcorearb.h from above
#define __gl_h_
#include <GL/glx.h>

#include "official/glxext.h"

struct GLWindowingData
{
	Display *dpy;
	GLXContext ctx;
	GLXDrawable wnd;
};

#else
#error "Unknown platform"
#endif

#include "api/replay/renderdoc_replay.h"

// similar to RDCUNIMPLEMENTED but for things that are hit often so we don't want to fire the debugbreak.
#define GLNOTIMP(...) RDCDEBUG("OpenGL not implemented - " __VA_ARGS__)

#define IMPLEMENT_FUNCTION_SERIALISED(ret, func) ret func; bool CONCAT(Serialise_, func);

class WrappedOpenGL;
struct GLHookSet;

size_t BufferIdx(GLenum buf);
GLenum BufferEnum(size_t idx);

size_t ShaderIdx(GLenum buf);
GLenum ShaderBit(size_t idx);
GLenum ShaderEnum(size_t idx);

ResourceFormat MakeResourceFormat(WrappedOpenGL &gl, GLenum target, GLenum fmt);
GLenum MakeGLFormat(WrappedOpenGL &gl, GLenum target, ResourceFormat fmt);

extern int GLCoreVersion;
void UpdateExtensionSupport(const GLHookSet &gl);
bool ExtensionSupported(const char *ext);

#include "serialise/serialiser.h"
#include "core/core.h"

void CopyProgramUniforms(const GLHookSet &gl, GLuint progSrc, GLuint progDst);
void SerialiseProgramUniforms(const GLHookSet &gl, Serialiser *ser, GLuint prog, bool writing);

enum GLChunkType
{
	DEVICE_INIT = FIRST_CHUNK_ID,

	GEN_TEXTURE,
	BIND_TEXTURE,
	BIND_TEXTURES,
	BIND_IMAGE_TEXTURE,
	BIND_IMAGE_TEXTURES,
	ACTIVE_TEXTURE,
	TEXSTORAGE1D,
	TEXSTORAGE2D,
	TEXSTORAGE3D,
	TEXSTORAGE2DMS,
	TEXSTORAGE3DMS,
	TEXIMAGE1D,
	TEXIMAGE2D,
	TEXIMAGE3D,
	TEXSUBIMAGE1D,
	TEXSUBIMAGE2D,
	TEXSUBIMAGE3D,
	TEXIMAGE1D_COMPRESSED,
	TEXIMAGE2D_COMPRESSED,
	TEXIMAGE3D_COMPRESSED,
	TEXSUBIMAGE1D_COMPRESSED,
	TEXSUBIMAGE2D_COMPRESSED,
	TEXSUBIMAGE3D_COMPRESSED,
	TEXBUFFER,
	TEXBUFFER_RANGE,
	PIXELSTORE,
	TEXPARAMETERF,
	TEXPARAMETERFV,
	TEXPARAMETERI,
	TEXPARAMETERIV,
	GENERATE_MIPMAP,
	COPY_SUBIMAGE,
	COPY_IMAGE1D,
	COPY_IMAGE2D,
	COPY_SUBIMAGE1D,
	COPY_SUBIMAGE2D,
	COPY_SUBIMAGE3D,
	TEXTURE_VIEW,

	CREATE_SHADER,
	CREATE_PROGRAM,
	CREATE_SHADERPROGRAM,
	COMPILESHADER,
	SHADERSOURCE,
	ATTACHSHADER,
	DETACHSHADER,
	USEPROGRAM,
	PROGRAMPARAMETER,
	BINDATTRIB_LOCATION,
	BINDFRAGDATA_LOCATION,
	UNIFORM_BLOCKBIND,
	STORAGE_BLOCKBIND,
	PROGRAMUNIFORM_VECTOR,
	PROGRAMUNIFORM_MATRIX,
	LINKPROGRAM,

	GEN_PROGRAMPIPE,
	USE_PROGRAMSTAGES,
	BIND_PROGRAMPIPE,

	FENCE_SYNC,
	CLIENTWAIT_SYNC,
	WAIT_SYNC,

	GEN_QUERIES,
	BEGIN_QUERY,
	END_QUERY,
	QUERY_COUNTER,

	CLEAR_COLOR,
	CLEAR_DEPTH,
	CLEAR_STENCIL,
	CLEAR,
	CLEARBUFFERF,
	CLEARBUFFERI,
	CLEARBUFFERUI,
	CLEARBUFFERFI,
	CLEARBUFFERDATA,
	CLEARBUFFERSUBDATA,
	CLEARTEXIMAGE,
	CLEARTEXSUBIMAGE,
	POLYGON_MODE,
	POLYGON_OFFSET,
	CULL_FACE,
	HINT,
	ENABLE,
	DISABLE,
	ENABLEI,
	DISABLEI,
	FRONT_FACE,
	BLEND_FUNC,
	BLEND_FUNCI,
	BLEND_COLOR,
	BLEND_FUNC_SEP,
	BLEND_FUNC_SEPI,
	BLEND_EQ,
	BLEND_EQI,
	BLEND_EQ_SEP,
	BLEND_EQ_SEPI,
	LOGIC_OP,
	STENCIL_OP,
	STENCIL_OP_SEP,
	STENCIL_FUNC,
	STENCIL_FUNC_SEP,
	STENCIL_MASK,
	STENCIL_MASK_SEP,
	COLOR_MASK,
	COLOR_MASKI,
	SAMPLE_MASK,
	SAMPLE_COVERAGE,
	DEPTH_FUNC,
	DEPTH_MASK,
	DEPTH_RANGE,
	DEPTH_RANGEF,
	DEPTH_RANGE_IDX,
	DEPTH_RANGEARRAY,
	DEPTH_BOUNDS,
	CLIP_CONTROL,
	PROVOKING_VERTEX,
	PRIMITIVE_RESTART,
	PATCH_PARAMI,
	PATCH_PARAMFV,
	LINE_WIDTH,
	POINT_SIZE,
	POINT_PARAMF,
	POINT_PARAMFV,
	POINT_PARAMI,
	POINT_PARAMIV,
	VIEWPORT,
	VIEWPORT_ARRAY,
	SCISSOR,
	SCISSOR_ARRAY,
	BIND_VERTEXBUFFER,
	BIND_VERTEXBUFFERS,
	VERTEXBINDINGDIVISOR,
	DISPATCH_COMPUTE,
	DISPATCH_COMPUTE_INDIRECT,
	MEMORY_BARRIER,
	DRAWARRAYS,
	DRAWARRAYS_INDIRECT,
	DRAWARRAYS_INSTANCED,
	DRAWARRAYS_INSTANCEDBASEINSTANCE,
	DRAWELEMENTS,
	DRAWELEMENTS_INDIRECT,
	DRAWRANGEELEMENTS,
	DRAWRANGEELEMENTSBASEVERTEX,
	DRAWELEMENTS_INSTANCED,
	DRAWELEMENTS_INSTANCEDBASEINSTANCE,
	DRAWELEMENTS_BASEVERTEX,
	DRAWELEMENTS_INSTANCEDBASEVERTEX,
	DRAWELEMENTS_INSTANCEDBASEVERTEXBASEINSTANCE,
	MULTI_DRAWARRAYS,
	MULTI_DRAWELEMENTS,

	GEN_FRAMEBUFFERS,
	FRAMEBUFFER_TEX,
	FRAMEBUFFER_TEX1D,
	FRAMEBUFFER_TEX2D,
	FRAMEBUFFER_TEX3D,
	FRAMEBUFFER_RENDBUF,
	FRAMEBUFFER_TEXLAYER,
	READ_BUFFER,
	BIND_FRAMEBUFFER,
	DRAW_BUFFER,
	DRAW_BUFFERS,
	BLIT_FRAMEBUFFER,

	GEN_RENDERBUFFERS,
	RENDERBUFFER_STORAGE,
	RENDERBUFFER_STORAGEMS,

	GEN_SAMPLERS,
	SAMPLER_PARAMETERI,
	SAMPLER_PARAMETERF,
	SAMPLER_PARAMETERIV,
	SAMPLER_PARAMETERFV,
	SAMPLER_PARAMETERIIV,
	SAMPLER_PARAMETERIUIV,
	BIND_SAMPLER,
	BIND_SAMPLERS,

	GEN_BUFFER,
	BIND_BUFFER,
	BIND_BUFFER_BASE,
	BIND_BUFFER_RANGE,
	BIND_BUFFERS_BASE,
	BIND_BUFFERS_RANGE,
	BUFFERSTORAGE,
	BUFFERDATA,
	BUFFERSUBDATA,
	COPYBUFFERSUBDATA,
	UNMAP,
	GEN_VERTEXARRAY,
	BIND_VERTEXARRAY,
	VERTEXATTRIB_GENERIC,
	VERTEXATTRIBPOINTER,
	VERTEXATTRIBIPOINTER,
	VERTEXATTRIBLPOINTER,
	ENABLEVERTEXATTRIBARRAY,
	DISABLEVERTEXATTRIBARRAY,
	VERTEXATTRIBFORMAT,
	VERTEXATTRIBIFORMAT,
	VERTEXATTRIBLFORMAT,
	VERTEXATTRIBDIVISOR,
	VERTEXATTRIBBINDING,
	
	OBJECT_LABEL,
	BEGIN_EVENT,
	SET_MARKER,
	END_EVENT,

	DEBUG_MESSAGES,

	CAPTURE_SCOPE,
	CONTEXT_CAPTURE_HEADER,
	CONTEXT_CAPTURE_FOOTER,

	NUM_OPENGL_CHUNKS,
};
