/* Generated by executing: $ typdef_gen.py egl.xml */

#ifndef EGL_FUNC_TYPEDEFS_H
#define EGL_FUNC_TYPEDEFS_H
#include "egl.h"
#include "eglext.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef EGLDisplay (*PFN_eglGetDisplay)(EGLNativeDisplayType display_id);
typedef EGLBoolean (*PFN_eglBindAPI)(EGLenum api);
typedef __eglMustCastToProperFunctionPointerType (*PFN_eglGetProcAddress)(const char *procname);
typedef EGLBoolean (*PFN_eglSwapBuffers)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglChooseConfig)(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config);
typedef EGLContext (*PFN_eglCreateContext)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list);
typedef EGLBoolean (*PFN_eglQuerySurface)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglGetConfigAttrib)(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglInitialize)(EGLDisplay dpy, EGLint *major, EGLint *minor);
typedef EGLBoolean (*PFN_eglMakeCurrent)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx);
typedef EGLSurface (*PFN_eglCreateWindowSurface)(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list);
typedef EGLint (*PFN_eglGetError)();
typedef EGLBoolean (*PFN_eglDestroySurface)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglDestroyContext)(EGLDisplay dpy, EGLContext ctx);
typedef EGLSurface (*PFN_eglCreatePbufferSurface)(EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list);
typedef EGLBoolean (*PFN_eglSwapInterval)(EGLDisplay dpy, EGLint interval);
typedef EGLSurface (*PFN_eglGetCurrentSurface)(EGLint readdraw);
typedef EGLDisplay (*PFN_eglGetCurrentDisplay)();
typedef EGLBoolean (*PFN_eglBindTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLint (*PFN_eglClientWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout);
typedef EGLint (*PFN_eglClientWaitSyncKHR)(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout);
typedef EGLint (*PFN_eglClientWaitSyncNV)(EGLSyncNV sync, EGLint flags, EGLTimeNV timeout);
typedef EGLBoolean (*PFN_eglCopyBuffers)(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target);
typedef EGLImageKHR (*PFN_eglCreateDRMImageMESA)(EGLDisplay dpy, const EGLint *attrib_list);
typedef EGLSyncNV (*PFN_eglCreateFenceSyncNV)(EGLDisplay dpy, EGLenum condition, const EGLint *attrib_list);
typedef EGLImage (*PFN_eglCreateImage)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib *attrib_list);
typedef EGLImageKHR (*PFN_eglCreateImageKHR)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLint *attrib_list);
typedef EGLClientBuffer (*PFN_eglCreateNativeClientBufferANDROID)(const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePbufferFromClientBuffer)(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePixmapSurface)(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePixmapSurfaceHI)(EGLDisplay dpy, EGLConfig config, struct EGLClientPixmapHI *pixmap);
typedef EGLSurface (*PFN_eglCreatePlatformPixmapSurface)(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLAttrib *attrib_list);
typedef EGLSurface (*PFN_eglCreatePlatformPixmapSurfaceEXT)(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePlatformWindowSurface)(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list);
typedef EGLSurface (*PFN_eglCreatePlatformWindowSurfaceEXT)(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLint *attrib_list);
typedef EGLStreamKHR (*PFN_eglCreateStreamFromFileDescriptorKHR)(EGLDisplay dpy, EGLNativeFileDescriptorKHR file_descriptor);
typedef EGLStreamKHR (*PFN_eglCreateStreamKHR)(EGLDisplay dpy, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreateStreamProducerSurfaceKHR)(EGLDisplay dpy, EGLConfig config, EGLStreamKHR stream, const EGLint *attrib_list);
typedef EGLSyncKHR (*PFN_eglCreateStreamSyncNV)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum type, const EGLint *attrib_list);
typedef EGLSync (*PFN_eglCreateSync)(EGLDisplay dpy, EGLenum type, const EGLAttrib *attrib_list);
typedef EGLSyncKHR (*PFN_eglCreateSyncKHR)(EGLDisplay dpy, EGLenum type, const EGLint *attrib_list);
typedef EGLSyncKHR (*PFN_eglCreateSync64KHR)(EGLDisplay dpy, EGLenum type, const EGLAttribKHR *attrib_list);
typedef EGLint (*PFN_eglDebugMessageControlKHR)(EGLDEBUGPROCKHR callback, const EGLAttrib *attrib_list);
typedef EGLBoolean (*PFN_eglDestroyImage)(EGLDisplay dpy, EGLImage image);
typedef EGLBoolean (*PFN_eglDestroyImageKHR)(EGLDisplay dpy, EGLImageKHR image);
typedef EGLBoolean (*PFN_eglDestroyStreamKHR)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (*PFN_eglDestroySync)(EGLDisplay dpy, EGLSync sync);
typedef EGLBoolean (*PFN_eglDestroySyncKHR)(EGLDisplay dpy, EGLSyncKHR sync);
typedef EGLBoolean (*PFN_eglDestroySyncNV)(EGLSyncNV sync);
typedef EGLint (*PFN_eglDupNativeFenceFDANDROID)(EGLDisplay dpy, EGLSyncKHR sync);
typedef EGLBoolean (*PFN_eglExportDMABUFImageMESA)(EGLDisplay dpy, EGLImageKHR image, int *fds, EGLint *strides, EGLint *offsets);
typedef EGLBoolean (*PFN_eglExportDMABUFImageQueryMESA)(EGLDisplay dpy, EGLImageKHR image, int *fourcc, int *num_planes, EGLuint64KHR *modifiers);
typedef EGLBoolean (*PFN_eglExportDRMImageMESA)(EGLDisplay dpy, EGLImageKHR image, EGLint *name, EGLint *handle, EGLint *stride);
typedef EGLBoolean (*PFN_eglFenceNV)(EGLSyncNV sync);
typedef EGLBoolean (*PFN_eglGetConfigs)(EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config);
typedef EGLContext (*PFN_eglGetCurrentContext)();
typedef EGLint (*PFN_eglGetError)();
typedef EGLBoolean (*PFN_eglGetOutputLayersEXT)(EGLDisplay dpy, const EGLAttrib *attrib_list, EGLOutputLayerEXT *layers, EGLint max_layers, EGLint *num_layers);
typedef EGLBoolean (*PFN_eglGetOutputPortsEXT)(EGLDisplay dpy, const EGLAttrib *attrib_list, EGLOutputPortEXT *ports, EGLint max_ports, EGLint *num_ports);
typedef EGLDisplay (*PFN_eglGetPlatformDisplay)(EGLenum platform, void *native_display, const EGLAttrib *attrib_list);
typedef EGLDisplay (*PFN_eglGetPlatformDisplayEXT)(EGLenum platform, void *native_display, const EGLint *attrib_list);
typedef EGLNativeFileDescriptorKHR (*PFN_eglGetStreamFileDescriptorKHR)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (*PFN_eglGetSyncAttrib)(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib *value);
typedef EGLBoolean (*PFN_eglGetSyncAttribKHR)(EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglGetSyncAttribNV)(EGLSyncNV sync, EGLint attribute, EGLint *value);
typedef EGLuint64NV (*PFN_eglGetSystemTimeFrequencyNV)();
typedef EGLuint64NV (*PFN_eglGetSystemTimeNV)();
typedef EGLint (*PFN_eglLabelObjectKHR)(EGLDisplay display, EGLenum objectType, EGLObjectKHR object, EGLLabelKHR label);
typedef EGLBoolean (*PFN_eglLockSurfaceKHR)(EGLDisplay dpy, EGLSurface surface, const EGLint *attrib_list);
typedef EGLBoolean (*PFN_eglOutputLayerAttribEXT)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (*PFN_eglOutputPortAttribEXT)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib value);
typedef EGLBoolean (*PFN_eglPostSubBufferNV)(EGLDisplay dpy, EGLSurface surface, EGLint x, EGLint y, EGLint width, EGLint height);
typedef EGLBoolean (*PFN_eglPresentationTimeANDROID)(EGLDisplay dpy, EGLSurface surface, EGLnsecsANDROID time);
typedef EGLenum (*PFN_eglQueryAPI)();
typedef EGLBoolean (*PFN_eglQueryContext)(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglQueryDebugKHR)(EGLint attribute, EGLAttrib *value);
typedef EGLBoolean (*PFN_eglQueryDeviceAttribEXT)(EGLDeviceEXT device, EGLint attribute, EGLAttrib *value);
typedef const char * (*PFN_eglQueryDeviceStringEXT)(EGLDeviceEXT device, EGLint name);
typedef EGLBoolean (*PFN_eglQueryDevicesEXT)(EGLint max_devices, EGLDeviceEXT *devices, EGLint *num_devices);
typedef EGLBoolean (*PFN_eglQueryDisplayAttribEXT)(EGLDisplay dpy, EGLint attribute, EGLAttrib *value);
typedef EGLBoolean (*PFN_eglQueryDisplayAttribNV)(EGLDisplay dpy, EGLint attribute, EGLAttrib *value);
typedef EGLBoolean (*PFN_eglQueryNativeDisplayNV)(EGLDisplay dpy, EGLNativeDisplayType *display_id);
typedef EGLBoolean (*PFN_eglQueryNativePixmapNV)(EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType *pixmap);
typedef EGLBoolean (*PFN_eglQueryNativeWindowNV)(EGLDisplay dpy, EGLSurface surf, EGLNativeWindowType *window);
typedef EGLBoolean (*PFN_eglQueryOutputLayerAttribEXT)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib *value);
typedef const char * (*PFN_eglQueryOutputLayerStringEXT)(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name);
typedef EGLBoolean (*PFN_eglQueryOutputPortAttribEXT)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib *value);
typedef const char * (*PFN_eglQueryOutputPortStringEXT)(EGLDisplay dpy, EGLOutputPortEXT port, EGLint name);
typedef EGLBoolean (*PFN_eglQueryStreamKHR)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglQueryStreamMetadataNV)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum name, EGLint n, EGLint offset, EGLint size, void *data);
typedef EGLBoolean (*PFN_eglQueryStreamTimeKHR)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLTimeKHR *value);
typedef EGLBoolean (*PFN_eglQueryStreamu64KHR)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLuint64KHR *value);
typedef const char * (*PFN_eglQueryString)(EGLDisplay dpy, EGLint name);
typedef EGLBoolean (*PFN_eglQuerySurface64KHR)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLAttribKHR *value);
typedef EGLBoolean (*PFN_eglQuerySurfacePointerANGLE)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, void **value);
typedef EGLBoolean (*PFN_eglReleaseTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (*PFN_eglReleaseThread)();
typedef void  (*PFN_eglSetBlobCacheFuncsANDROID)(EGLDisplay dpy, EGLSetBlobFuncANDROID set, EGLGetBlobFuncANDROID get);
typedef EGLBoolean (*PFN_eglSetDamageRegionKHR)(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects);
typedef EGLBoolean (*PFN_eglSetStreamMetadataNV)(EGLDisplay dpy, EGLStreamKHR stream, EGLint n, EGLint offset, EGLint size, const void *data);
typedef EGLBoolean (*PFN_eglSignalSyncKHR)(EGLDisplay dpy, EGLSyncKHR sync, EGLenum mode);
typedef EGLBoolean (*PFN_eglSignalSyncNV)(EGLSyncNV sync, EGLenum mode);
typedef EGLBoolean (*PFN_eglStreamAttribKHR)(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint value);
typedef EGLBoolean (*PFN_eglStreamConsumerAcquireKHR)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (*PFN_eglStreamConsumerGLTextureExternalKHR)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (*PFN_eglStreamConsumerGLTextureExternalAttribsNV)(EGLDisplay dpy, EGLStreamKHR stream, EGLAttrib *attrib_list);
typedef EGLBoolean (*PFN_eglStreamConsumerOutputEXT)(EGLDisplay dpy, EGLStreamKHR stream, EGLOutputLayerEXT layer);
typedef EGLBoolean (*PFN_eglStreamConsumerReleaseKHR)(EGLDisplay dpy, EGLStreamKHR stream);
typedef EGLBoolean (*PFN_eglSurfaceAttrib)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value);
typedef EGLBoolean (*PFN_eglSwapBuffers)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglSwapBuffersWithDamageEXT)(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects);
typedef EGLBoolean (*PFN_eglSwapBuffersWithDamageKHR)(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects);
typedef EGLBoolean (*PFN_eglSwapBuffersRegionNOK)(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint *rects);
typedef EGLBoolean (*PFN_eglSwapBuffersRegion2NOK)(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint *rects);

typedef EGLBoolean (*PFN_eglTerminate)(EGLDisplay dpy);
typedef EGLBoolean (*PFN_eglUnlockSurfaceKHR)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglWaitClient)();
typedef EGLBoolean (*PFN_eglWaitGL)();
typedef EGLBoolean (*PFN_eglWaitNative)(EGLint engine);
typedef EGLBoolean (*PFN_eglWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags);
typedef EGLint (*PFN_eglWaitSyncKHR)(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags);

#ifdef __cplusplus
}
#endif

#endif /* EGL_FUNC_TYPEDEFS_H */
