/* Generated by executing: $ ./typdef_gen.py egl.xml */

#ifndef EGL_FUNC_TYPEDEFS_H
#define EGL_FUNC_TYPEDEFS_H

#include "egl.h"
#include "eglext.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef EGL_VERSION_1_0
typedef EGLBoolean (*PFN_eglChooseConfig)(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config);
typedef EGLBoolean (*PFN_eglCopyBuffers)(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target);
typedef EGLContext (*PFN_eglCreateContext)(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePbufferSurface)(EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreatePixmapSurface)(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list);
typedef EGLSurface (*PFN_eglCreateWindowSurface)(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list);
typedef EGLBoolean (*PFN_eglDestroyContext)(EGLDisplay dpy, EGLContext ctx);
typedef EGLBoolean (*PFN_eglDestroySurface)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglGetConfigAttrib)(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglGetConfigs)(EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config);
typedef EGLDisplay (*PFN_eglGetCurrentDisplay)();
typedef EGLSurface (*PFN_eglGetCurrentSurface)(EGLint readdraw);
typedef EGLDisplay (*PFN_eglGetDisplay)(EGLNativeDisplayType display_id);
typedef EGLint (*PFN_eglGetError)();
typedef __eglMustCastToProperFunctionPointerType (*PFN_eglGetProcAddress)(const char *procname);
typedef EGLBoolean (*PFN_eglInitialize)(EGLDisplay dpy, EGLint *major, EGLint *minor);
typedef EGLBoolean (*PFN_eglMakeCurrent)(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx);
typedef EGLBoolean (*PFN_eglQueryContext)(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value);
typedef const char * (*PFN_eglQueryString)(EGLDisplay dpy, EGLint name);
typedef EGLBoolean (*PFN_eglQuerySurface)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value);
typedef EGLBoolean (*PFN_eglSwapBuffers)(EGLDisplay dpy, EGLSurface surface);
typedef EGLBoolean (*PFN_eglTerminate)(EGLDisplay dpy);
typedef EGLBoolean (*PFN_eglWaitGL)();
typedef EGLBoolean (*PFN_eglWaitNative)(EGLint engine);
#endif

#ifdef EGL_VERSION_1_1
typedef EGLBoolean (*PFN_eglBindTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (*PFN_eglReleaseTexImage)(EGLDisplay dpy, EGLSurface surface, EGLint buffer);
typedef EGLBoolean (*PFN_eglSurfaceAttrib)(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value);
typedef EGLBoolean (*PFN_eglSwapInterval)(EGLDisplay dpy, EGLint interval);
#endif

#ifdef EGL_VERSION_1_2
typedef EGLBoolean (*PFN_eglBindAPI)(EGLenum api);
typedef EGLenum (*PFN_eglQueryAPI)();
typedef EGLSurface (*PFN_eglCreatePbufferFromClientBuffer)(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list);
typedef EGLBoolean (*PFN_eglReleaseThread)();
typedef EGLBoolean (*PFN_eglWaitClient)();
#endif

#ifdef EGL_VERSION_1_3
#endif

#ifdef EGL_VERSION_1_4
typedef EGLContext (*PFN_eglGetCurrentContext)();
#endif

#ifdef EGL_VERSION_1_5
#ifdef EGL_KHR_fence_sync
typedef EGLSync (*PFN_eglCreateSync)(EGLDisplay dpy, EGLenum type, const EGLAttrib *attrib_list);
typedef EGLBoolean (*PFN_eglDestroySync)(EGLDisplay dpy, EGLSync sync);
typedef EGLint (*PFN_eglClientWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout);
typedef EGLBoolean (*PFN_eglGetSyncAttrib)(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib *value);
#endif
#ifdef EGL_KHR_image_base
typedef EGLImage (*PFN_eglCreateImage)(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib *attrib_list);
typedef EGLBoolean (*PFN_eglDestroyImage)(EGLDisplay dpy, EGLImage image);
#endif
#ifdef EGL_EXT_platform_base
typedef EGLDisplay (*PFN_eglGetPlatformDisplay)(EGLenum platform, void *native_display, const EGLAttrib *attrib_list);
typedef EGLSurface (*PFN_eglCreatePlatformWindowSurface)(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list);
typedef EGLSurface (*PFN_eglCreatePlatformPixmapSurface)(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLAttrib *attrib_list);
#endif
#ifdef EGL_KHR_wait_sync
typedef EGLBoolean (*PFN_eglWaitSync)(EGLDisplay dpy, EGLSync sync, EGLint flags);
#endif
#endif


#ifdef __cplusplus
}
#endif

#endif /* EGL_FUNC_TYPEDEFS_H */
