/******************************************************************************
 * The MIT License (MIT)
 *
 * Copyright (c) 2015-2016 Baldur Karlsson
 * Copyright (c) 2014 Crytek
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 ******************************************************************************/

#pragma once

#include "gles_common.h"

struct GLHookSet
{
  // ++ dllexport
  PFNGLACTIVESHADERPROGRAMPROC glActiveShaderProgram;
  PFNGLACTIVETEXTUREPROC glActiveTexture;    // aliases glActiveTextureARB
  PFNGLATTACHSHADERPROC glAttachShader;
  PFNGLBEGINQUERYPROC glBeginQuery;    // aliases glBeginQueryARB
  PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;    // aliases glBeginTransformFeedbackEXT
  PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
  PFNGLBINDBUFFERBASEPROC glBindBufferBase;      // aliases glBindBufferBaseEXT
  PFNGLBINDBUFFERPROC glBindBuffer;                        // aliases glBindBufferARB
  PFNGLBINDBUFFERRANGEPROC glBindBufferRange;    // aliases glBindBufferRangeEXT
  PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;              // aliases glBindFramebufferEXT
  PFNGLBINDIMAGETEXTUREPROC glBindImageTexture;    // aliases glBindImageTextureEXT
  PFNGLBINDPROGRAMPIPELINEPROC glBindProgramPipeline;
  PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;          // aliases glBindRenderbufferEXT
  PFNGLBINDSAMPLERPROC glBindSampler;
  PFNGLBINDTEXTUREPROC glBindTexture;
  PFNGLBINDTRANSFORMFEEDBACKPROC glBindTransformFeedback;
  PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
  PFNGLBINDVERTEXBUFFERPROC glBindVertexBuffer;
  PFNGLBLENDBARRIERPROC glBlendBarrier;
  PFNGLBLENDCOLORPROC glBlendColor;                    // aliases glBlendColorEXT
  PFNGLBLENDEQUATIONIPROC glBlendEquationi;            // aliases glBlendEquationiARB
  PFNGLBLENDEQUATIONPROC glBlendEquation;              // aliases glBlendEquationEXT
  PFNGLBLENDEQUATIONSEPARATEIPROC glBlendEquationSeparatei;    // aliases glBlendEquationSeparateiARB
  PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;    // aliases glBlendEquationSeparateARB, glBlendEquationSeparateEXT
  PFNGLBLENDFUNCIPROC glBlendFunci;                    // aliases glBlendFunciARB
  PFNGLBLENDFUNCPROC glBlendFunc;
  PFNGLBLENDFUNCSEPARATEIPROC glBlendFuncSeparatei;    // aliases glBlendFuncSeparateiARB
  PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;      // aliases glBlendFuncSeparateARB
  PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;    // aliases glBlitFramebufferEXT
  PFNGLBUFFERDATAPROC glBufferData;          // aliases glBufferDataARB
  PFNGLBUFFERSUBDATAPROC glBufferSubData;    // aliases glBufferSubDataARB
  PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;                            // aliases glCheckFramebufferStatusEXT
  PFNGLCLEARBUFFERFIPROC glClearBufferfi;
  PFNGLCLEARBUFFERFVPROC glClearBufferfv;
  PFNGLCLEARBUFFERIVPROC glClearBufferiv;
  PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
  PFNGLCLEARCOLORPROC glClearColor;
  PFNGLCLEARDEPTHFPROC glClearDepthf;
  PFNGLCLEARPROC glClear;
  PFNGLCLEARSTENCILPROC glClearStencil;
  PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
  PFNGLCOLORMASKIPROC glColorMaski;    // aliases glColorMaskIndexedEXT
  PFNGLCOLORMASKPROC glColorMask;
  PFNGLCOMPILESHADERPROC glCompileShader;
  PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;    // aliases glCompressedTexImage2DARB
  PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;    // aliases glCompressedTexImage3DARB
  PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;    // aliases glCompressedTexSubImage2DARB
  PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;    // aliases glCompressedTexSubImage3DARB
  PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
  PFNGLCOPYIMAGESUBDATAPROC glCopyImageSubData;
  PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
  PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
  PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
  PFNGLCREATEPROGRAMPROC glCreateProgram;
  PFNGLCREATESHADERPROC glCreateShader;
  PFNGLCREATESHADERPROGRAMVPROC glCreateShaderProgramv;
  PFNGLCULLFACEPROC glCullFace;
  PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback;    // aliases glDebugMessageCallbackARB
  PFNGLDEBUGMESSAGECONTROLPROC glDebugMessageControl;      // aliases glDebugMessageControlARB
  PFNGLDEBUGMESSAGEINSERTPROC glDebugMessageInsert;        // aliases glDebugMessageInsertARB
  PFNGLDELETEBUFFERSPROC glDeleteBuffers;    // aliases glDeleteBuffersARB
  PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;      // aliases glDeleteFramebuffersEXT
  PFNGLDELETEPROGRAMPIPELINESPROC glDeleteProgramPipelines;
  PFNGLDELETEPROGRAMPROC glDeleteProgram;
  PFNGLDELETEQUERIESPROC glDeleteQueries;    // aliases glDeleteQueriesARB
  PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;    // aliases glDeleteRenderbuffersEXT
  PFNGLDELETESAMPLERSPROC glDeleteSamplers;
  PFNGLDELETESHADERPROC glDeleteShader;
  PFNGLDELETESYNCPROC glDeleteSync;
  PFNGLDELETETEXTURESPROC glDeleteTextures;
  PFNGLDELETETRANSFORMFEEDBACKSPROC glDeleteTransformFeedbacks;
  PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
  PFNGLDEPTHFUNCPROC glDepthFunc;
  PFNGLDEPTHMASKPROC glDepthMask;
  PFNGLDEPTHRANGEFPROC glDepthRangef;
  PFNGLDETACHSHADERPROC glDetachShader;
  PFNGLDISABLEIPROC glDisablei;              // aliases glDisableIndexedEXT
  PFNGLDISABLEPROC glDisable;
  PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;    // aliases glDisableVertexAttribArrayARB
  PFNGLDISPATCHCOMPUTEINDIRECTPROC glDispatchComputeIndirect;
  PFNGLDISPATCHCOMPUTEPROC glDispatchCompute;
  PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect;
  PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;    // aliases glDrawArraysInstancedARB, glDrawArraysInstancedEXT
  PFNGLDRAWARRAYSPROC glDrawArrays;
  PFNGLDRAWBUFFERSPROC glDrawBuffers;
  PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
  PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect;
  PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
  PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;    // aliases glDrawElementsInstancedARB, glDrawElementsInstancedEXT
  PFNGLDRAWELEMENTSPROC glDrawElements;
  PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
  PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;    // aliases glDrawRangeElementsEXT
  PFNGLENABLEIPROC glEnablei;                // aliases glEnableIndexedEXT
  PFNGLENABLEPROC glEnable;
  PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;    // aliases glEnableVertexAttribArrayARB
  PFNGLENDQUERYPROC glEndQuery;    // aliases glEndQueryARB
  PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;    // aliases glEndTransformFeedbackEXT
  PFNGLFENCESYNCPROC glFenceSync;
  PFNGLFINISHPROC glFinish;
  PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
  PFNGLFLUSHPROC glFlush;
  PFNGLFRAMEBUFFERPARAMETERIPROC glFramebufferParameteri;
  PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;    // aliases glFramebufferRenderbufferEXT
  PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;    // aliases glFramebufferTexture2DEXT
  PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;    // aliases
  PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;        // aliases glFramebufferTextureARB
  PFNGLFRONTFACEPROC glFrontFace;
  PFNGLGENBUFFERSPROC glGenBuffers;                        // aliases glGenBuffersARB
  PFNGLGENERATEMIPMAPPROC glGenerateMipmap;        // aliases glGenerateMipmapEXT
  PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;              // aliases glGenFramebuffersEXT
  PFNGLGENPROGRAMPIPELINESPROC glGenProgramPipelines;
  PFNGLGENQUERIESPROC glGenQueries;    // aliases glGenQueriesARB
  PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;          // aliases glGenRenderbuffersEXT
  PFNGLGENSAMPLERSPROC glGenSamplers;
  PFNGLGENTEXTURESPROC glGenTextures;
  PFNGLGENTRANSFORMFEEDBACKSPROC glGenTransformFeedbacks;
  PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
  PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
  PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
  PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
  PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
  PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
  PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
  PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
  PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
  PFNGLGETBOOLEANVPROC glGetBooleanv;
  PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
  PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;    // aliases glGetBufferParameterivARB
  PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;    // aliases glGetBufferPointervARB
  PFNGLGETDEBUGMESSAGELOGPROC glGetDebugMessageLog;    // aliases glGetDebugMessageLogARB
  PFNGLGETERRORPROC glGetError;
  PFNGLGETFLOATVPROC glGetFloatv;
  PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;    // aliases glGetFragDataLocationEXT
  PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;    // aliases glGetFramebufferAttachmentParameterivEXT
  PFNGLGETFRAMEBUFFERPARAMETERIVPROC glGetFramebufferParameteriv;
  PFNGLGETGRAPHICSRESETSTATUSPROC glGetGraphicsResetStatus;    // aliases glGetGraphicsResetStatusARB
  PFNGLGETINTEGER64I_VPROC glGetInteger64i_v;
  PFNGLGETINTEGER64VPROC glGetInteger64v;
  PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
  PFNGLGETINTEGERVPROC glGetIntegerv;
  PFNGLGETINTERNALFORMATIVPROC glGetInternalformativ;
  PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv;
  PFNGLGETNUNIFORMFVPROC glGetnUniformfv;                // aliases glGetnUniformfvARB
  PFNGLGETNUNIFORMIVPROC glGetnUniformiv;                // aliases glGetnUniformivARB
  PFNGLGETNUNIFORMUIVPROC glGetnUniformuiv;              // aliases glGetnUniformuivARB
  PFNGLGETOBJECTLABELPROC glGetObjectLabel;
  PFNGLGETOBJECTPTRLABELPROC glGetObjectPtrLabel;
  PFNGLGETPOINTERVPROC glGetPointerv;
  PFNGLGETPROGRAMBINARYPROC glGetProgramBinary;
  PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
  PFNGLGETPROGRAMINTERFACEIVPROC glGetProgramInterfaceiv;
  PFNGLGETPROGRAMIVPROC glGetProgramiv;
  PFNGLGETPROGRAMPIPELINEINFOLOGPROC glGetProgramPipelineInfoLog;
  PFNGLGETPROGRAMPIPELINEIVPROC glGetProgramPipelineiv;
  PFNGLGETPROGRAMRESOURCEINDEXPROC glGetProgramResourceIndex;
  PFNGLGETPROGRAMRESOURCEIVPROC glGetProgramResourceiv;
  PFNGLGETPROGRAMRESOURCELOCATIONPROC glGetProgramResourceLocation;
  PFNGLGETPROGRAMRESOURCENAMEPROC glGetProgramResourceName;
  PFNGLGETQUERYIVPROC glGetQueryiv;                      // aliases glGetQueryivARB
  PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;        // aliases glGetQueryObjectuivARB
  PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;    // aliases glGetRenderbufferParameterivEXT
  PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
  PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
  PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
  PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
  PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
  PFNGLGETSHADERIVPROC glGetShaderiv;
  PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
  PFNGLGETSHADERSOURCEPROC glGetShaderSource;
  PFNGLGETSTRINGIPROC glGetStringi;
  PFNGLGETSTRINGPROC glGetString;
  PFNGLGETSYNCIVPROC glGetSynciv;
  PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
  PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
  PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
  PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;      // aliases glGetTexParameterIivEXT
  PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;    // aliases glGetTexParameterIuivEXT
  PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
  PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;    // aliases glGetTransformFeedbackVaryingEXT
  PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
  PFNGLGETUNIFORMFVPROC glGetUniformfv;
  PFNGLGETUNIFORMINDICESPROC glGetUniformIndices;
  PFNGLGETUNIFORMIVPROC glGetUniformiv;
  PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
  PFNGLGETUNIFORMUIVPROC glGetUniformuiv;    // aliases glGetUniformuivEXT
  PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
  PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;      // aliases glGetVertexAttribIivEXT
  PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;    // aliases glGetVertexAttribIuivEXT
  PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
  PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
  PFNGLHINTPROC glHint;
  PFNGLINVALIDATEFRAMEBUFFERPROC glInvalidateFramebuffer;
  PFNGLINVALIDATESUBFRAMEBUFFERPROC glInvalidateSubFramebuffer;
  PFNGLISBUFFERPROC glIsBuffer;              // aliases glIsBufferARB
  PFNGLISENABLEDIPROC glIsEnabledi;          // aliases glIsEnabledIndexedEXT
  PFNGLISENABLEDPROC glIsEnabled;
  PFNGLISFRAMEBUFFERPROC glIsFramebuffer;    // aliases glIsFramebufferEXT
  PFNGLISPROGRAMPIPELINEPROC glIsProgramPipeline;
  PFNGLISPROGRAMPROC glIsProgram;
  PFNGLISQUERYPROC glIsQuery;                  // aliases glIsQueryARB
  PFNGLISRENDERBUFFERPROC glIsRenderbuffer;    // aliases glIsRenderbufferEXT
  PFNGLISSAMPLERPROC glIsSampler;
  PFNGLISSHADERPROC glIsShader;
  PFNGLISSYNCPROC glIsSync;
  PFNGLISTEXTUREPROC glIsTexture;
  PFNGLISTRANSFORMFEEDBACKPROC glIsTransformFeedback;
  PFNGLISVERTEXARRAYPROC glIsVertexArray;
  PFNGLLINEWIDTHPROC glLineWidth;
  PFNGLLINKPROGRAMPROC glLinkProgram;
  PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
  PFNGLMEMORYBARRIERBYREGIONPROC glMemoryBarrierByRegion;
  PFNGLMEMORYBARRIERPROC glMemoryBarrier;    // aliases glMemoryBarrierEXT
  PFNGLMINSAMPLESHADINGPROC glMinSampleShading;    // aliases glMinSampleShadingARB
  PFNGLOBJECTLABELPROC glObjectLabel;
  PFNGLOBJECTPTRLABELPROC glObjectPtrLabel;
  PFNGLPATCHPARAMETERIPROC glPatchParameteri;
  PFNGLPAUSETRANSFORMFEEDBACKPROC glPauseTransformFeedback;
  PFNGLPIXELSTOREIPROC glPixelStorei;
  PFNGLPOLYGONOFFSETPROC glPolygonOffset;
  PFNGLPOPDEBUGGROUPPROC glPopDebugGroup;
  PFNGLPRIMITIVEBOUNDINGBOXPROC glPrimitiveBoundingBox;
  PFNGLPROGRAMBINARYPROC glProgramBinary;
  PFNGLPROGRAMPARAMETERIPROC glProgramParameteri;    // aliases glProgramParameteriARB
  PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f;        // aliases glProgramUniform1fEXT
  PFNGLPROGRAMUNIFORM1FVPROC glProgramUniform1fv;      // aliases glProgramUniform1fvEXT
  PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i;        // aliases glProgramUniform1iEXT
  PFNGLPROGRAMUNIFORM1IVPROC glProgramUniform1iv;      // aliases glProgramUniform1ivEXT
  PFNGLPROGRAMUNIFORM1UIPROC glProgramUniform1ui;      // aliases glProgramUniform1uiEXT
  PFNGLPROGRAMUNIFORM1UIVPROC glProgramUniform1uiv;    // aliases glProgramUniform1uivEXT
  PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f;        // aliases glProgramUniform2fEXT
  PFNGLPROGRAMUNIFORM2FVPROC glProgramUniform2fv;      // aliases glProgramUniform2fvEXT
  PFNGLPROGRAMUNIFORM2IPROC glProgramUniform2i;        // aliases glProgramUniform2iEXT
  PFNGLPROGRAMUNIFORM2IVPROC glProgramUniform2iv;      // aliases glProgramUniform2ivEXT
  PFNGLPROGRAMUNIFORM2UIPROC glProgramUniform2ui;      // aliases glProgramUniform2uiEXT
  PFNGLPROGRAMUNIFORM2UIVPROC glProgramUniform2uiv;    // aliases glProgramUniform2uivEXT
  PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f;        // aliases glProgramUniform3fEXT
  PFNGLPROGRAMUNIFORM3FVPROC glProgramUniform3fv;      // aliases glProgramUniform3fvEXT
  PFNGLPROGRAMUNIFORM3IPROC glProgramUniform3i;        // aliases glProgramUniform3iEXT
  PFNGLPROGRAMUNIFORM3IVPROC glProgramUniform3iv;      // aliases glProgramUniform3ivEXT
  PFNGLPROGRAMUNIFORM3UIPROC glProgramUniform3ui;      // aliases glProgramUniform3uiEXT
  PFNGLPROGRAMUNIFORM3UIVPROC glProgramUniform3uiv;    // aliases glProgramUniform3uivEXT
  PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f;        // aliases glProgramUniform4fEXT
  PFNGLPROGRAMUNIFORM4FVPROC glProgramUniform4fv;      // aliases glProgramUniform4fvEXT
  PFNGLPROGRAMUNIFORM4IPROC glProgramUniform4i;        // aliases glProgramUniform4iEXT
  PFNGLPROGRAMUNIFORM4IVPROC glProgramUniform4iv;      // aliases glProgramUniform4ivEXT
  PFNGLPROGRAMUNIFORM4UIPROC glProgramUniform4ui;      // aliases glProgramUniform4uiEXT
  PFNGLPROGRAMUNIFORM4UIVPROC glProgramUniform4uiv;    // aliases glProgramUniform4uivEXT
  PFNGLPROGRAMUNIFORMMATRIX2FVPROC glProgramUniformMatrix2fv;    // aliases glProgramUniformMatrix2fvEXT
  PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glProgramUniformMatrix2x3fv;    // aliases glProgramUniformMatrix2x3fvEXT
  PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glProgramUniformMatrix2x4fv;    // aliases glProgramUniformMatrix2x4fvEXT
  PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv;    // aliases glProgramUniformMatrix3fvEXT
  PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glProgramUniformMatrix3x2fv;    // aliases glProgramUniformMatrix3x2fvEXT
  PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glProgramUniformMatrix3x4fv;    // aliases glProgramUniformMatrix3x4fvEXT
  PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv;    // aliases glProgramUniformMatrix4fvEXT
  PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glProgramUniformMatrix4x2fv;    // aliases glProgramUniformMatrix4x2fvEXT
  PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glProgramUniformMatrix4x3fv;    // aliases glProgramUniformMatrix4x3fvEXT
  PFNGLPUSHDEBUGGROUPPROC glPushDebugGroup;
  PFNGLREADBUFFERPROC glReadBuffer;
  PFNGLREADNPIXELSPROC glReadnPixels;                    // aliases glReadnPixelsARB
  PFNGLREADPIXELSPROC glReadPixels;
  PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;    // aliases glRenderbufferStorageMultisampleEXT
  PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;    // aliases glRenderbufferStorageEXT
  PFNGLRESUMETRANSFORMFEEDBACKPROC glResumeTransformFeedback;
  PFNGLSAMPLECOVERAGEPROC glSampleCoverage;        // aliases glSampleCoverageARB
  PFNGLSAMPLEMASKIPROC glSampleMaski;
  PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;
  PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
  PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
  PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
  PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
  PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
  PFNGLSCISSORPROC glScissor;
  PFNGLSHADERBINARYPROC glShaderBinary;
  PFNGLSHADERSOURCEPROC glShaderSource;
  PFNGLSTENCILFUNCPROC glStencilFunc;
  PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
  PFNGLSTENCILMASKPROC glStencilMask;
  PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
  PFNGLSTENCILOPPROC glStencilOp;
  PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
  PFNGLTEXBUFFERPROC glTexBuffer;    // aliases glTexBufferARB, glTexBufferEXT
  PFNGLTEXBUFFERRANGEPROC glTexBufferRange;
  PFNGLTEXIMAGE2DPROC glTexImage2D;
  PFNGLTEXIMAGE3DPROC glTexImage3D;    // aliases glTexImage3DEXT
  PFNGLTEXPARAMETERFPROC glTexParameterf;
  PFNGLTEXPARAMETERFVPROC glTexParameterfv;
  PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;      // aliases glTexParameterIivEXT
  PFNGLTEXPARAMETERIPROC glTexParameteri;
  PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;    // aliases glTexParameterIuivEXT
  PFNGLTEXPARAMETERIVPROC glTexParameteriv;
  PFNGLTEXSTORAGE2DMULTISAMPLEPROC glTexStorage2DMultisample;
  PFNGLTEXSTORAGE2DPROC glTexStorage2D;
  PFNGLTEXSTORAGE3DMULTISAMPLEPROC glTexStorage3DMultisample;
  PFNGLTEXSTORAGE3DPROC glTexStorage3D;
  PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
  PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
  PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;    // aliases glTransformFeedbackVaryingsEXT
  PFNGLUNIFORM1FPROC glUniform1f;
  PFNGLUNIFORM1FVPROC glUniform1fv;
  PFNGLUNIFORM1IPROC glUniform1i;
  PFNGLUNIFORM1IVPROC glUniform1iv;
  PFNGLUNIFORM1UIPROC glUniform1ui;    // aliases glUniform1uiEXT
  PFNGLUNIFORM1UIVPROC glUniform1uiv;    // aliases glUniform1uivEXT
  PFNGLUNIFORM2FPROC glUniform2f;
  PFNGLUNIFORM2FVPROC glUniform2fv;
  PFNGLUNIFORM2IPROC glUniform2i;
  PFNGLUNIFORM2IVPROC glUniform2iv;
  PFNGLUNIFORM2UIPROC glUniform2ui;    // aliases glUniform2uiEXT
  PFNGLUNIFORM2UIVPROC glUniform2uiv;    // aliases glUniform2uivEXT
  PFNGLUNIFORM3FPROC glUniform3f;
  PFNGLUNIFORM3FVPROC glUniform3fv;
  PFNGLUNIFORM3IPROC glUniform3i;
  PFNGLUNIFORM3IVPROC glUniform3iv;
  PFNGLUNIFORM3UIPROC glUniform3ui;    // aliases glUniform3uiEXT
  PFNGLUNIFORM3UIVPROC glUniform3uiv;    // aliases glUniform3uivEXT
  PFNGLUNIFORM4FPROC glUniform4f;
  PFNGLUNIFORM4FVPROC glUniform4fv;
  PFNGLUNIFORM4IPROC glUniform4i;
  PFNGLUNIFORM4IVPROC glUniform4iv;
  PFNGLUNIFORM4UIPROC glUniform4ui;    // aliases glUniform4uiEXT
  PFNGLUNIFORM4UIVPROC glUniform4uiv;    // aliases glUniform4uivEXT
  PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
  PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
  PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
  PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
  PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
  PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
  PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
  PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
  PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
  PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
  PFNGLUNMAPBUFFERPROC glUnmapBuffer;    // aliases glUnmapBufferARB
  PFNGLUSEPROGRAMPROC glUseProgram;
  PFNGLUSEPROGRAMSTAGESPROC glUseProgramStages;
  PFNGLVALIDATEPROGRAMPIPELINEPROC glValidateProgramPipeline;
  PFNGLVALIDATEPROGRAMPROC glValidateProgram;
  PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;        // aliases glVertexAttrib1fARB
  PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;      // aliases glVertexAttrib1fvARB
  PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;        // aliases glVertexAttrib2fARB
  PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;      // aliases glVertexAttrib2fvARB
  PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;        // aliases glVertexAttrib3fARB
  PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;      // aliases glVertexAttrib3fvARB
  PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;          // aliases glVertexAttrib4fARB
  PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;        // aliases glVertexAttrib4fvARB
  PFNGLVERTEXATTRIBBINDINGPROC glVertexAttribBinding;
  PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;    // aliases glVertexAttribDivisorARB
  PFNGLVERTEXATTRIBFORMATPROC glVertexAttribFormat;
  PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;        // aliases glVertexAttribI4iEXT
  PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;      // aliases glVertexAttribI4ivEXT
  PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;      // aliases glVertexAttribI4uiEXT
  PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;    // aliases glVertexAttribI4uivEXT
  PFNGLVERTEXATTRIBIFORMATPROC glVertexAttribIFormat;
  PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;    // aliases glVertexAttribIPointerEXT
  PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;      // aliases glVertexAttribPointerARB
  PFNGLVERTEXBINDINGDIVISORPROC glVertexBindingDivisor;
  PFNGLVIEWPORTPROC glViewport;
  PFNGLWAITSYNCPROC glWaitSync;
  // --
  
  // ++ glext
  PFNGLACTIVESHADERPROGRAMEXTPROC glActiveShaderProgramExt;
  PFNGLALPHAFUNCQCOMPROC glAlphaFuncQCom;
  PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC glApplyFrameBufferAttachmentCMAAINTEL;
  PFNGLBEGINCONDITIONALRENDERNVPROC glBeginConditionalRenderNV;
  PFNGLBEGINPERFMONITORAMDPROC glBeginPerfMonitorAMD;
  PFNGLBEGINPERFQUERYINTELPROC glBeginPerfQueryINTEL;
  PFNGLBEGINQUERYEXTPROC glBeginQueryExt;    // aliases glBeginQueryARB
  PFNGLBINDFRAGDATALOCATIONEXTPROC glBindFragDataLocationEXT;
  PFNGLBINDFRAGDATALOCATIONINDEXEDEXTPROC glBindFragDataLocationIndexedEXT;
  PFNGLBINDPROGRAMPIPELINEEXTPROC glBindProgramPipelineEXT;
  PFNGLBINDVERTEXARRAYOESPROC glBindVertexArrayOES;
  PFNGLBLENDBARRIERKHRPROC glBlendBarrierKHR;
  PFNGLBLENDBARRIERNVPROC glBlendBarrierNV;
  PFNGLBLENDEQUATIONIEXTPROC glBlendEquationiEXT;            // aliases glBlendEquationiARB
  PFNGLBLENDEQUATIONIOESPROC glBlendEquationiOES;            // aliases glBlendEquationEXT
  PFNGLBLENDEQUATIONSEPARATEIEXTPROC glBlendEquationSeparateiEXT;    // aliases glBlendEquationSeparateiARB
  PFNGLBLENDEQUATIONSEPARATEIOESPROC glBlendEquationSeparateiOES;    // aliases glBlendEquationSeparateiARB
  PFNGLBLENDFUNCIEXTPROC glBlendFunciEXT;                    // aliases glBlendFunciARB
  PFNGLBLENDFUNCIOESPROC glBlendFunciOES;                    // aliases glBlendFunciARB
  PFNGLBLENDFUNCSEPARATEIEXTPROC glBlendFuncSeparateiEXT;    // aliases glBlendFuncSeparateiARB
  PFNGLBLENDFUNCSEPARATEIOESPROC glBlendFuncSeparateiOES;    // aliases glBlendFuncSeparateiARB
  PFNGLBLENDPARAMETERINVPROC glBlendParameteriNV;
  PFNGLBLITFRAMEBUFFERANGLEPROC glBlitFramebufferAngle;
  PFNGLBLITFRAMEBUFFERNVPROC glBlitFramebufferNV;    // aliases glBlitFramebufferEXT
  PFNGLBUFFERSTORAGEEXTPROC glBufferStorageEXT;
  PFNGLCLEARPIXELLOCALSTORAGEUIEXTPROC glClearPixelLocalStorageuiEXT;
  PFNGLCLIENTWAITSYNCAPPLEPROC glClientWaitSyncAPPLE;
  PFNGLCOLORMASKIEXTPROC glColorMaskiEXT;    // aliases glColorMaskIndexedEXT
  PFNGLCOLORMASKIOESPROC glColorMaskiOES;    // aliases glColorMaskIndexedEXT
  PFNGLCOMPRESSEDTEXIMAGE3DOESPROC glCompressedTexImage3DOES;    // aliases glCompressedTexImage3DARB
  PFNGLCOMPRESSEDTEXSUBIMAGE3DOESPROC glCompressedTexSubImage3DOES;    // aliases glCompressedTexSubImage3DARB
  PFNGLCONSERVATIVERASTERPARAMETERINVPROC glConservativeRasterParameteriNV;
  PFNGLCOPYBUFFERSUBDATANVPROC glCopyBufferSubDataNV;
  PFNGLCOPYIMAGESUBDATAEXTPROC glCopyImageSubDataEXT;
  PFNGLCOPYIMAGESUBDATAOESPROC glCopyImageSubDataOES;
  PFNGLCOPYPATHNVPROC glCopyPathNV;
  PFNGLCOPYTEXSUBIMAGE3DOESPROC glCopyTexSubImage3DOES;
  PFNGLCOPYTEXTURELEVELSAPPLEPROC glCopyTextureLevelSapple;
  PFNGLCOVERAGEMASKNVPROC glCoverageMaskNV;
  PFNGLCOVERAGEMODULATIONNVPROC glCoverageModulationNV;
  PFNGLCOVERAGEMODULATIONTABLENVPROC glCoverageModulationTableNV;
  PFNGLCOVERAGEOPERATIONNVPROC glCoverageOperationNV;
  PFNGLCOVERFILLPATHINSTANCEDNVPROC glCoverFillPathInstancedNV;
  PFNGLCOVERFILLPATHNVPROC glCoverFillPathNV;
  PFNGLCOVERSTROKEPATHINSTANCEDNVPROC glCoverStrokePathInstancedNV;
  PFNGLCOVERSTROKEPATHNVPROC glCoverStrokePathNV;
  PFNGLCREATEPERFQUERYINTELPROC glCreatePerfQueryINTEL;
  PFNGLCREATESHADERPROGRAMVEXTPROC glCreateShaderProgramvEXT;
  PFNGLDEBUGMESSAGECALLBACKKHRPROC glDebugMessageCallbackKHR;    // aliases glDebugMessageCallbackARB
  PFNGLDEBUGMESSAGECONTROLKHRPROC glDebugMessageControlKHR;      // aliases glDebugMessageControlARB
  PFNGLDEBUGMESSAGEINSERTKHRPROC glDebugMessageInsertKHR;        // aliases glDebugMessageInsertARB
  PFNGLDELETEFENCESNVPROC glDeleteFencesNV;
  PFNGLDELETEPATHSNVPROC glDeletePathsNV;
  PFNGLDELETEPERFMONITORSAMDPROC glDeletePerfmonitorsAMD;
  PFNGLDELETEPERFQUERYINTELPROC glDeletePerfQueryINTEL;
  PFNGLDELETEPROGRAMPIPELINESEXTPROC glDeleteProgramPipelinesEXT;
  PFNGLDELETEQUERIESEXTPROC glDeleteQueriesEXT;    // aliases glDeleteQueriesARB
  PFNGLDELETESYNCAPPLEPROC glDeleteSyncAPPLE;
  PFNGLDELETEVERTEXARRAYSOESPROC glDeleteVertexArraysOES;
  PFNGLDEPTHRANGEARRAYFVNVPROC glDepthRangeArrayfvNV;
  PFNGLDEPTHRANGEARRAYFVOESPROC glDepthRangeArrayfvOES;
  PFNGLDEPTHRANGEINDEXEDFNVPROC glDepthRangeIndexedfNV;
  PFNGLDEPTHRANGEINDEXEDFOESPROC glDepthRangeIndexedfOES;
  PFNGLDISABLEDRIVERCONTROLQCOMPROC glDisableDriverControlQCom;
  PFNGLDISABLEIEXTPROC glDisableiEXT;              // aliases glDisableIndexedEXT
  PFNGLDISABLEINVPROC glDisableiNV;              // aliases glDisableIndexedEXT
  PFNGLDISABLEIOESPROC glDisableiOES;              // aliases glDisableIndexedEXT
  PFNGLDISCARDFRAMEBUFFEREXTPROC glDiscardFrameBufferEXT;
  PFNGLDRAWARRAYSINSTANCEDANGLEPROC glDrawArraysInstancedAngle;
  PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEEXTPROC glDrawArraysInstancedBaseInstanceEXT;
  PFNGLDRAWARRAYSINSTANCEDEXTPROC glDrawArraysInstancedEXT;    // aliases glDrawArraysInstancedARB, glDrawArraysInstancedEXT
  PFNGLDRAWARRAYSINSTANCEDNVPROC glDrawArraysInstancedNV;    // aliases glDrawArraysInstancedARB, glDrawArraysInstancedEXT
  PFNGLDRAWBUFFERSEXTPROC glDrawBuffersEXT;          // aliases glDrawBuffersARB
  PFNGLDRAWBUFFERSINDEXEDEXTPROC glDrawBuffersIndexedEXT;
  PFNGLDRAWBUFFERSNVPROC glDrawBuffersNV;                      
  PFNGLDRAWELEMENTSBASEVERTEXEXTPROC glDrawElementsBaseVertexEXT;
  PFNGLDRAWELEMENTSBASEVERTEXOESPROC glDrawElementsBaseVertexOES;
  PFNGLDRAWELEMENTSINSTANCEDANGLEPROC glDrawElementsInstancedAngle;
  PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEEXTPROC glDrawElementsInstancedBaseInstanceEXT;
  PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEEXTPROC glDrawElementsInstancedBaseVertexBaseInstanceEXT;
  PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXEXTPROC glDrawElementsInstancedBaseVertexEXT;
  PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXOESPROC glDrawElementsInstancedBaseVertexOES;
  PFNGLDRAWELEMENTSINSTANCEDEXTPROC glDrawElementsInstancedEXT;    // aliases glDrawElementsInstancedARB, glDrawElementsInstancedEXT
  PFNGLDRAWELEMENTSINSTANCEDNVPROC glDrawElementsInstancedNV;    // aliases glDrawElementsInstancedARB, glDrawElementsInstancedEXT
  PFNGLDRAWRANGEELEMENTSBASEVERTEXEXTPROC glDrawRangeElementsBaseVertexEXT;
  PFNGLDRAWRANGEELEMENTSBASEVERTEXOESPROC glDrawRangeElementsBaseVertexOES;
  PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOESPROC glEGLImageTargetRenderBuffersStorageOES;
  PFNGLEGLIMAGETARGETTEXTURE2DOESPROC glEGLImageTargetTexture2DOES;
  PFNGLENABLEDRIVERCONTROLQCOMPROC glEnableDriverControlQCom;
  PFNGLENABLEIEXTPROC glEnableiEXT;                // aliases glEnableIndexedEXT
  PFNGLENABLEINVPROC glEnableiNV;                // aliases glEnableIndexedEXT
  PFNGLENABLEIOESPROC glEnableiOES;                // aliases glEnableIndexedEXT
  PFNGLENDCONDITIONALRENDERNVPROC glEndConditionalRenderNV;
  PFNGLENDPERFMONITORAMDPROC glPerfMonitorAMD;
  PFNGLENDPERFQUERYINTELPROC glEndPerfQueryINTEL;
  PFNGLENDQUERYEXTPROC glEndQueryEXT;// aliases glEndQueryARB
  PFNGLENDTILINGQCOMPROC glEndTilingCom;
  PFNGLEXTGETBUFFERPOINTERVQCOMPROC glExtGetBufferPointervQCom;
  PFNGLEXTGETBUFFERSQCOMPROC glExtGetBuffersQCom;
  PFNGLEXTGETFRAMEBUFFERSQCOMPROC glExtGetFrameBuffersQCom;
  PFNGLEXTGETPROGRAMBINARYSOURCEQCOMPROC glExtGetProgramBinarySourceQCom;
  PFNGLEXTGETPROGRAMSQCOMPROC glExtGetProgramsQCom;
  PFNGLEXTGETRENDERBUFFERSQCOMPROC glExtGetRenderBuffersQCom;
  PFNGLEXTGETSHADERSQCOMPROC glExtGeShadersQCom;
  PFNGLEXTGETTEXLEVELPARAMETERIVQCOMPROC glExtGetTexlLevelParameterivQCom;
  PFNGLEXTGETTEXSUBIMAGEQCOMPROC glExtGetTexSubImageQCom;
  PFNGLEXTGETTEXTURESQCOMPROC glExtGetTexturesQCom;
  PFNGLEXTISPROGRAMBINARYQCOMPROC glExtIsProgramBinaryQCom;
  PFNGLEXTTEXOBJECTSTATEOVERRIDEIQCOMPROC glExtTexObjectStateOverrideiQCom;
  PFNGLFENCESYNCAPPLEPROC glFenceSyncAPPLE;
  PFNGLFINISHFENCENVPROC glFinishFenceNV;
  PFNGLFLUSHMAPPEDBUFFERRANGEEXTPROC glFlushMappedBufferRangeEXT;
  PFNGLFRAGMENTCOVERAGECOLORNVPROC glFragmentCoverageColorNV;
  PFNGLFRAMEBUFFERPIXELLOCALSTORAGESIZEEXTPROC glFrameBufferPixelLocalStorageSizeExt;
  PFNGLFRAMEBUFFERSAMPLELOCATIONSFVNVPROC glFrameBufferSampleLocationsfvNV;
  PFNGLFRAMEBUFFERTEXTURE2DDOWNSAMPLEIMGPROC glFrameBufferTexture2DDownSampleIMG;
  PFNGLFRAMEBUFFERTEXTURE2DMULTISAMPLEEXTPROC glFramebufferTexture2DMultisampleEXT;
  PFNGLFRAMEBUFFERTEXTURE2DMULTISAMPLEIMGPROC glFramebufferTexture2DMultisampleIMG;
  PFNGLFRAMEBUFFERTEXTURE3DOESPROC glFramebufferTexture3DOES;
  PFNGLFRAMEBUFFERTEXTUREEXTPROC glFramebufferTextureEXT;
  PFNGLFRAMEBUFFERTEXTURELAYERDOWNSAMPLEIMGPROC glFramebufferTextureLayerDownsampleIMG;
  PFNGLFRAMEBUFFERTEXTUREMULTISAMPLEMULTIVIEWOVRPROC glFramebufferTextureMiltisampleMiltiviewOVR;
  PFNGLFRAMEBUFFERTEXTUREMULTIVIEWOVRPROC glFramebufferTextureMultiviewOVR;
  PFNGLFRAMEBUFFERTEXTUREOESPROC glFramebufferTextureOES;        // aliases glFramebufferTextureARB
  PFNGLGENFENCESNVPROC glGenFencesNV;
  PFNGLGENPATHSNVPROC glGenPathsNV;
  PFNGLGENPERFMONITORSAMDPROC glGenPerfMonitorsAMD;
  PFNGLGENPROGRAMPIPELINESEXTPROC glGenProgramPipelinesEXT;
  PFNGLGENQUERIESEXTPROC glGenQueriesEXT;    // aliases glGenQueriesARB
  PFNGLGENVERTEXARRAYSOESPROC glGenVertexArraysOES;
  PFNGLGETBUFFERPOINTERVOESPROC glGetBufferPointervOES;    // aliases glGetBufferPointervARB
  PFNGLGETCOVERAGEMODULATIONTABLENVPROC glGetCoverageModulationTableNV;
  PFNGLGETDEBUGMESSAGELOGKHRPROC glGetDebugMessageLogKHR;    // aliases glGetDebugMessageLogARB
  PFNGLGETDRIVERCONTROLSQCOMPROC glGetDriverControlsQCom;
  PFNGLGETDRIVERCONTROLSTRINGQCOMPROC glGetDriverControlStringQCom;
  PFNGLGETFENCEIVNVPROC glGetFenceivNV;
  PFNGLGETFIRSTPERFQUERYIDINTELPROC glGetFirstPerfQueryIdINTEL;
  PFNGLGETFLOATI_VNVPROC glGetFloati_vNV;
  PFNGLGETFLOATI_VOESPROC glGetFloati_vOES;
  PFNGLGETFRAGDATAINDEXEXTPROC glGetFragDataIndexEXT;
  PFNGLGETFRAMEBUFFERPIXELLOCALSTORAGESIZEEXTPROC glGetFramebufferPixelLocalStorageSizeEXT;
  PFNGLGETGRAPHICSRESETSTATUSEXTPROC glGetGraphicsResetStatusEXT;    // aliases glGetGraphicsResetStatusARB
  PFNGLGETGRAPHICSRESETSTATUSKHRPROC glGetGraphicsResetStatusKHR;    // aliases glGetGraphicsResetStatusARB
  PFNGLGETIMAGEHANDLENVPROC glGetImageHandleNV;
  PFNGLGETINTEGER64VAPPLEPROC glGetInteger64vAPPLE;
  PFNGLGETINTEGERI_VEXTPROC glGetIntegeri_vEXT;
  PFNGLGETINTERNALFORMATSAMPLEIVNVPROC glGetInternalformatSampleivNV;
  PFNGLGETNEXTPERFQUERYIDINTELPROC glGetNextPerfQueryIdINTEL;
  PFNGLGETNUNIFORMFVEXTPROC glGetnUniformfvEXT;                // aliases glGetnUniformfvARB
  PFNGLGETNUNIFORMFVKHRPROC glGetnUniformfvKHR;                // aliases glGetnUniformfvARB
  PFNGLGETNUNIFORMIVEXTPROC glGetnUniformivEXT;                // aliases glGetnUniformivARB
  PFNGLGETNUNIFORMIVKHRPROC glGetnUniformivKHR;                // aliases glGetnUniformivARB
  PFNGLGETNUNIFORMUIVKHRPROC glGetnUniformuivKHR;                // aliases glGetnUniformuivARB
  PFNGLGETOBJECTLABELEXTPROC glGetObjectLabelEXT;
  PFNGLGETOBJECTLABELKHRPROC glGetObjectLabelKHR;
  PFNGLGETOBJECTPTRLABELKHRPROC glGetObjectPtrLabelKHR;
  PFNGLGETPATHCOMMANDSNVPROC glGetPathCommandsNV;
  PFNGLGETPATHCOORDSNVPROC glGetPathCoordsNV;
  PFNGLGETPATHDASHARRAYNVPROC glGetPathDashArrayNV;
  PFNGLGETPATHLENGTHNVPROC glGetPathLengthNV;
  PFNGLGETPATHMETRICRANGENVPROC glGetPathMetricRangeNV;
  PFNGLGETPATHMETRICSNVPROC glGetPathMetricsNV;
  PFNGLGETPATHPARAMETERFVNVPROC glGetPathParameterfvNV;
  PFNGLGETPATHPARAMETERIVNVPROC glGetPathParameterivNV;
  PFNGLGETPATHSPACINGNVPROC glGetPathSpacingNV;
  PFNGLGETPERFCOUNTERINFOINTELPROC glGetPerfCounterInfoINTEL;
  PFNGLGETPERFMONITORCOUNTERDATAAMDPROC glGetPerfMonitorCounterDataAMD;
  PFNGLGETPERFMONITORCOUNTERINFOAMDPROC glGetPerfMonitorCounterInfoAMD;
  PFNGLGETPERFMONITORCOUNTERSAMDPROC glGetPerfMonitorCountersAMD;
  PFNGLGETPERFMONITORCOUNTERSTRINGAMDPROC glGetPerfMonitorCounterStringAMD;
  PFNGLGETPERFMONITORGROUPSAMDPROC glGetPerfMonitorGroupsAMD;
  PFNGLGETPERFMONITORGROUPSTRINGAMDPROC glGetPerfMonitorGroupStringAMD;
  PFNGLGETPERFQUERYDATAINTELPROC glGetPerfQueryDataINTEL;
  PFNGLGETPERFQUERYIDBYNAMEINTELPROC glGetPerfQueryIdByNameINTEL;
  PFNGLGETPERFQUERYINFOINTELPROC glGetPerfQueryInfoINTEL;
  PFNGLGETPOINTERVKHRPROC glGetPointervKHR;
  PFNGLGETPROGRAMBINARYOESPROC glGetProgramBinaryOES;
  PFNGLGETPROGRAMPIPELINEINFOLOGEXTPROC glGetProgramPipelineInfoLogEXT;
  PFNGLGETPROGRAMPIPELINEIVEXTPROC glGetProgramPipelineivEXT;
  PFNGLGETPROGRAMRESOURCEFVNVPROC glGetProgramResourcfvNV;
  PFNGLGETPROGRAMRESOURCELOCATIONINDEXEXTPROC glGetProgramResourceLocationIndexEXT;
  PFNGLGETQUERYIVEXTPROC glGetQueryivEXT;                      // aliases glGetQueryivARB
  PFNGLGETQUERYOBJECTI64VEXTPROC glGetQueryObjecti64vEXT;
  PFNGLGETQUERYOBJECTIVEXTPROC glGetQueryObjectivEXT;
  PFNGLGETQUERYOBJECTUI64VEXTPROC glGetQueryObjectui64vEXT;
  PFNGLGETQUERYOBJECTUIVEXTPROC glGetQueryObjectuivEXT;
  PFNGLGETSAMPLERPARAMETERIIVEXTPROC glGetSamplerParameterIivEXT;
  PFNGLGETSAMPLERPARAMETERIIVOESPROC glGetSamplerParameterIivOES;
  PFNGLGETSAMPLERPARAMETERIUIVEXTPROC glGetSamplerParameterIuivEXT;
  PFNGLGETSAMPLERPARAMETERIUIVOESPROC glGetSamplerParameterIuivOES;
  PFNGLGETSYNCIVAPPLEPROC glGetSyncivAPPLE;
  PFNGLGETTEXPARAMETERIIVEXTPROC glGetTexParameterIivEXT;
  PFNGLGETTEXPARAMETERIIVOESPROC glGetTexParameterIivOES; // aliases glGetTexParameterIivEXT
  PFNGLGETTEXPARAMETERIUIVEXTPROC glGetTexParameterIuivEXT; 
  PFNGLGETTEXPARAMETERIUIVOESPROC glGetTexParameterIuivOES; // aliases glGetTexParameterIuivEXT
  PFNGLGETTEXTUREHANDLENVPROC glGetTextureHandleNV;
  PFNGLGETTEXTURESAMPLERHANDLENVPROC glGetTextureSamplerHandleNV;
  PFNGLGETTRANSLATEDSHADERSOURCEANGLEPROC glGetTranslatedShaderSourceAngle;
  PFNGLGETUNIFORMI64VNVPROC glGetUniformi64vNV;
  PFNGLINSERTEVENTMARKEREXTPROC glInsertEventMarkerEXT;
  PFNGLINTERPOLATEPATHSNVPROC glInterpolatePathsNV;
  PFNGLISENABLEDIEXTPROC glIsEnablediEXT;
  PFNGLISENABLEDINVPROC glIsEnablediNV;
  PFNGLISENABLEDIOESPROC glIsEnablediOES;
  PFNGLISFENCENVPROC glIsFenceNV;
  PFNGLISIMAGEHANDLERESIDENTNVPROC glIsImageHandleResidentNV;
  PFNGLISPATHNVPROC glIsPathNV;
  PFNGLISPOINTINFILLPATHNVPROC glIsPointInFillPathNV;
  PFNGLISPOINTINSTROKEPATHNVPROC glIsPointInStrokePathNV;
  PFNGLISPROGRAMPIPELINEEXTPROC glIsProgramPipelineEXT;
  PFNGLISQUERYEXTPROC glIsQueryEXT;                  // aliases glIsQueryARB
  PFNGLISSYNCAPPLEPROC glIsSyncAPPLE;
  PFNGLISTEXTUREHANDLERESIDENTNVPROC glIsTextureHandleResidentNV;
  PFNGLISVERTEXARRAYOESPROC glIsVertexArrayOES;
  PFNGLLABELOBJECTEXTPROC glLabelObjectEXT;
  PFNGLMAKEIMAGEHANDLENONRESIDENTNVPROC glMakeImageHandleNonResidentNV;
  PFNGLMAKEIMAGEHANDLERESIDENTNVPROC glMakeImageHandleResidentNV;
  PFNGLMAKETEXTUREHANDLENONRESIDENTNVPROC glMakeTextureHandleNonResidentNV;
  PFNGLMAKETEXTUREHANDLERESIDENTNVPROC glMakeTextureHandleResidentNV;
  PFNGLMAPBUFFEROESPROC glMapBufferOES;    // aliases glMapBufferARB
  PFNGLMAPBUFFERRANGEEXTPROC glMapBufferRangeEXT;
  PFNGLMATRIXLOAD3X2FNVPROC glMatrixLoad3x2fNV;
  PFNGLMATRIXLOAD3X3FNVPROC glMatrixLoad3x3fNV;
  PFNGLMATRIXLOADTRANSPOSE3X3FNVPROC glMatrixLoadTranspose3x3fNV;
  PFNGLMATRIXMULT3X2FNVPROC glMatrixMult3x2fNV;
  PFNGLMATRIXMULT3X3FNVPROC glMatrixMult3x3fNV;
  PFNGLMATRIXMULTTRANSPOSE3X3FNVPROC glMatrixMultTranspose3x3fNV;
  PFNGLMINSAMPLESHADINGOESPROC glMinSampleShadingOES;    // aliases glMinSampleShadingARB
  PFNGLMULTIDRAWARRAYSEXTPROC glMultiDrawArraysEXT;
  PFNGLMULTIDRAWARRAYSINDIRECTEXTPROC glMultiDrawArraysIndirectEXT;
  PFNGLMULTIDRAWELEMENTSBASEVERTEXEXTPROC glMultiDrawElementsBaseVertexEXT;
  PFNGLMULTIDRAWELEMENTSBASEVERTEXOESPROC glMultiDrawElementsBaseVertexOES;
  PFNGLMULTIDRAWELEMENTSEXTPROC glMultiDrawElementsEXT;
  PFNGLMULTIDRAWELEMENTSINDIRECTEXTPROC glMultiDrawElementsIndirectEXT;
  PFNGLNAMEDFRAMEBUFFERSAMPLELOCATIONSFVNVPROC glNamedFramebufferSampleLocationsfvNV;
  PFNGLOBJECTLABELKHRPROC glObjectLabelKHR;
  PFNGLOBJECTPTRLABELKHRPROC glObjectPtrLabelKHR;
  PFNGLPATCHPARAMETERIEXTPROC glPatchParameteriEXT;
  PFNGLPATCHPARAMETERIOESPROC glPatchParameteriOES;
  PFNGLPATHCOMMANDSNVPROC glPathCommandsNV;
  PFNGLPATHCOORDSNVPROC glPathCoordsNV;
  PFNGLPATHCOVERDEPTHFUNCNVPROC glPathCoverDepthFuncNV;
  PFNGLPATHDASHARRAYNVPROC glPathDashArrayNV;
  PFNGLPATHGLYPHINDEXARRAYNVPROC glPathGlyphIndexArrayNV;
  PFNGLPATHGLYPHINDEXRANGENVPROC glPathGlyphIndexRangeNV;
  PFNGLPATHGLYPHRANGENVPROC glPathGlyphRangeNV;
  PFNGLPATHGLYPHSNVPROC glPathGlyphsNV;
  PFNGLPATHMEMORYGLYPHINDEXARRAYNVPROC glPathMemoryGlyphIndexArrayNV;
  PFNGLPATHPARAMETERFNVPROC glPathParameterfNV;
  PFNGLPATHPARAMETERFVNVPROC glPathParameterfvNV;
  PFNGLPATHPARAMETERINVPROC glPathParameteriNV;
  PFNGLPATHPARAMETERIVNVPROC glPathParameterivNV;
  PFNGLPATHSTENCILDEPTHOFFSETNVPROC glPathStencilDepthOffsetNV;
  PFNGLPATHSTENCILFUNCNVPROC glPathStencilFuncNV;
  PFNGLPATHSTRINGNVPROC glPathStringNV;
  PFNGLPATHSUBCOMMANDSNVPROC glPathSubCommandsNV;
  PFNGLPATHSUBCOORDSNVPROC glPathSubCoordsNV;
  PFNGLPOINTALONGPATHNVPROC glPointAlongPathNV;
  PFNGLPOLYGONMODENVPROC glPolygonModeNV;
  PFNGLPOLYGONOFFSETCLAMPEXTPROC glPolygonOffsetClampEXT;
  PFNGLPOPDEBUGGROUPKHRPROC glPopDebugGroupKHR;
  PFNGLPOPGROUPMARKEREXTPROC glPopGroupMarkerEXT;
  PFNGLPRIMITIVEBOUNDINGBOXEXTPROC glPrimitiveBoundingBoxEXT;
  PFNGLPRIMITIVEBOUNDINGBOXOESPROC glPrimitiveBoundingBoxOES;
  PFNGLPROGRAMBINARYOESPROC glProgramBinaryOES;
  PFNGLPROGRAMPARAMETERIEXTPROC glProgramParameteriEXT;    // aliases glProgramParameteriARB
  PFNGLPROGRAMPATHFRAGMENTINPUTGENNVPROC glProgramPathFragmentInputGenNV;
  PFNGLPROGRAMUNIFORM1FEXTPROC glProgramUniform1fEXT;
  PFNGLPROGRAMUNIFORM1FVEXTPROC glProgramUniform1fvEXT; 
  PFNGLPROGRAMUNIFORM1I64NVPROC glProgramUniform1i64NV;
  PFNGLPROGRAMUNIFORM1I64VNVPROC glProgramUniform1i64vNV;
  PFNGLPROGRAMUNIFORM1IEXTPROC glProgramUniform1iEXT;
  PFNGLPROGRAMUNIFORM1IVEXTPROC glProgramUniform1ivEXT;
  PFNGLPROGRAMUNIFORM1UI64NVPROC glProgramUniform1ui64NV;
  PFNGLPROGRAMUNIFORM1UI64VNVPROC glProgramUniform1ui64vNV;
  PFNGLPROGRAMUNIFORM1UIEXTPROC glProgramUniform1uiEXT;
  PFNGLPROGRAMUNIFORM1UIVEXTPROC glProgramUniform1uivEXT;
  PFNGLPROGRAMUNIFORM2FEXTPROC glProgramUniform2fEXT;
  PFNGLPROGRAMUNIFORM2FVEXTPROC glProgramUniform2fvEXT;
  PFNGLPROGRAMUNIFORM2I64NVPROC glProgramUniform2i64NV;
  PFNGLPROGRAMUNIFORM2I64VNVPROC glProgramUniform2i64vNV;
  PFNGLPROGRAMUNIFORM2IEXTPROC glProgramUniform2iEXT;
  PFNGLPROGRAMUNIFORM2IVEXTPROC glProgramUniform2ivEXT;
  PFNGLPROGRAMUNIFORM2UI64NVPROC glProgramUniform2ui64NV;
  PFNGLPROGRAMUNIFORM2UI64VNVPROC glProgramUniform2ui64vNV;
  PFNGLPROGRAMUNIFORM2UIEXTPROC glProgramUniform2uiEXT;
  PFNGLPROGRAMUNIFORM2UIVEXTPROC glProgramUniform2uivEXT;
  PFNGLPROGRAMUNIFORM3FEXTPROC glProgramUniform3fEXT;
  PFNGLPROGRAMUNIFORM3FVEXTPROC glProgramUniform3fvEXT;
  PFNGLPROGRAMUNIFORM3I64NVPROC glProgramUniform3i64NV;
  PFNGLPROGRAMUNIFORM3I64VNVPROC glProgramUniform3i64vNV;
  PFNGLPROGRAMUNIFORM3IEXTPROC glProgramUniform3iEXT;
  PFNGLPROGRAMUNIFORM3IVEXTPROC glProgramUniform3ivEXT;
  PFNGLPROGRAMUNIFORM3UI64NVPROC glProgramUniform3ui64NV;
  PFNGLPROGRAMUNIFORM3UI64VNVPROC glProgramUniform3ui64vNV;
  PFNGLPROGRAMUNIFORM3UIEXTPROC glProgramUniform3uiEXT;
  PFNGLPROGRAMUNIFORM3UIVEXTPROC glProgramUniform3uivEXT;
  PFNGLPROGRAMUNIFORM4FEXTPROC glProgramUniform4fEXT;
  PFNGLPROGRAMUNIFORM4FVEXTPROC glProgramUniform4fvEXT;
  PFNGLPROGRAMUNIFORM4I64NVPROC glProgramUniform4i64NV;
  PFNGLPROGRAMUNIFORM4I64VNVPROC glProgramUniform4i64vNV;
  PFNGLPROGRAMUNIFORM4IEXTPROC glProgramUniform4iEXT;
  PFNGLPROGRAMUNIFORM4IVEXTPROC glProgramUniform4ivEXT;
  PFNGLPROGRAMUNIFORM4UI64NVPROC glProgramUniform4ui64NV;
  PFNGLPROGRAMUNIFORM4UI64VNVPROC glProgramUniform4ui64vNV;
  PFNGLPROGRAMUNIFORM4UIEXTPROC glProgramUniform4uiEXT;
  PFNGLPROGRAMUNIFORM4UIVEXTPROC glProgramUniform4uivEXT;
  PFNGLPROGRAMUNIFORMHANDLEUI64NVPROC glProgramUniformHandleui64NV;
  PFNGLPROGRAMUNIFORMHANDLEUI64VNVPROC glProgramUniformHandleui64vNV;
  PFNGLPROGRAMUNIFORMMATRIX2FVEXTPROC glProgramUniformMatrix2fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX2X3FVEXTPROC glProgramUniformMatrix2x3fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX2X4FVEXTPROC glProgramUniformMatrix2x4fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX3FVEXTPROC glProgramUniformMatrix3fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX3X2FVEXTPROC glProgramUniformMatrix3x2fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX3X4FVEXTPROC glProgramUniformMatrix3x4fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX4FVEXTPROC glProgramUniformMatrix4fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX4X2FVEXTPROC glProgramUniformMatrix4x2fvEXT;
  PFNGLPROGRAMUNIFORMMATRIX4X3FVEXTPROC glProgramUniformMatrix4x3fvEXT;
  PFNGLPUSHDEBUGGROUPKHRPROC glPushDebugGroupKHR;
  PFNGLPUSHGROUPMARKEREXTPROC glPushGroupMarkerEXT;
  PFNGLQUERYCOUNTEREXTPROC glQueryCounterEXT;
  PFNGLRASTERSAMPLESEXTPROC glRasterSamplesEXT;
  PFNGLREADBUFFERINDEXEDEXTPROC glReadBufferIndexedEXT;
  PFNGLREADBUFFERNVPROC glReadBufferNV;
  PFNGLREADNPIXELSEXTPROC glReadnPixelsEXT;                    // aliases glReadnPixelsARB
  PFNGLREADNPIXELSKHRPROC glReadnPixelsKHR;                    // aliases glReadnPixelsARB
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLEANGLEPROC glRenderbufferStorageMultisampleAngle;
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLEAPPLEPROC glRenderbufferStorageMultisampleAPPLE;    // aliases glRenderbufferStorageMultisampleEXT
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC glRenderbufferStorageMultisampleEXT;    // aliases glRenderbufferStorageMultisampleEXT
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLEIMGPROC glRenderbufferStorageMultisampleIMG;    // aliases glRenderbufferStorageMultisampleEXT
  PFNGLRENDERBUFFERSTORAGEMULTISAMPLENVPROC glRenderbufferStorageMultisampleNV;    // aliases glRenderbufferStorageMultisampleEXT
  PFNGLRESOLVEDEPTHVALUESNVPROC glResolveDepthValuesNV;
  PFNGLRESOLVEMULTISAMPLEFRAMEBUFFERAPPLEPROC glResolveMultisampleFramebufferAPPLE;
  PFNGLSAMPLERPARAMETERIIVEXTPROC glSamplerParameterIivEXT;
  PFNGLSAMPLERPARAMETERIIVOESPROC glSamplerParameterIivOES;
  PFNGLSAMPLERPARAMETERIUIVEXTPROC glSamplerParameterIuivEXT;
  PFNGLSAMPLERPARAMETERIUIVOESPROC glSamplerParameterIuivOES;
  PFNGLSCISSORARRAYVNVPROC glScissorArrayvNV;
  PFNGLSCISSORARRAYVOESPROC glScissorArrayvOES;
  PFNGLSCISSORINDEXEDNVPROC glScissorIndexedNV;
  PFNGLSCISSORINDEXEDOESPROC glScissorIndexedOES;
  PFNGLSCISSORINDEXEDVNVPROC glScissorIndexedvNV;
  PFNGLSCISSORINDEXEDVOESPROC glScissorIndexedvOES;
  PFNGLSELECTPERFMONITORCOUNTERSAMDPROC glSelectPerfMonitorCountersAMD;
  PFNGLSETFENCENVPROC glSetFenceNV;
  PFNGLSTARTTILINGQCOMPROC glStartTilingQCom;
  PFNGLSTENCILFILLPATHINSTANCEDNVPROC glStencilFillPathInstancedNV;
  PFNGLSTENCILFILLPATHNVPROC glStencilFillPathNV;
  PFNGLSTENCILSTROKEPATHINSTANCEDNVPROC glStencilStrokePathInstancedNV;
  PFNGLSTENCILSTROKEPATHNVPROC glStencilStrokePathNV;
  PFNGLSTENCILTHENCOVERFILLPATHINSTANCEDNVPROC glStencilThenCoverFillPathInstancedNV;
  PFNGLSTENCILTHENCOVERFILLPATHNVPROC glStencilThenCoverFillPathNV;
  PFNGLSTENCILTHENCOVERSTROKEPATHINSTANCEDNVPROC glStencilThenCoverStrokePathInstancedNV;
  PFNGLSTENCILTHENCOVERSTROKEPATHNVPROC glStencilThenCoverStrokePathNV;
  PFNGLSUBPIXELPRECISIONBIASNVPROC glSubpixelPrecisionBiasNV;
  PFNGLTESTFENCENVPROC glTestFenceNV;
  PFNGLTEXBUFFEREXTPROC glTexBufferEXT;    // aliases glTexBufferARB, glTexBufferEXT
  PFNGLTEXBUFFEROESPROC glTexBufferOES;    // aliases glTexBufferARB, glTexBufferEXT
  PFNGLTEXBUFFERRANGEEXTPROC glTexBufferRangeEXT;
  PFNGLTEXBUFFERRANGEOESPROC glTexBufferRangeOES;
  PFNGLTEXIMAGE3DOESPROC glTexImage3DOES;    // aliases glTexImage3DEXT
  PFNGLTEXPAGECOMMITMENTEXTPROC glTexPageCommitmentEXT;
  PFNGLTEXPARAMETERIIVEXTPROC glTexParameterIivEXT;      // aliases glTexParameterIivEXT
  PFNGLTEXPARAMETERIIVOESPROC glTexParameterIivOES;      // aliases glTexParameterIivEXT
  PFNGLTEXPARAMETERIUIVEXTPROC glTexParameterIuivEXT;    // aliases glTexParameterIuivEXT
  PFNGLTEXPARAMETERIUIVOESPROC glTexParameterIuivOES;    // aliases glTexParameterIuivEXT
  PFNGLTEXSTORAGE1DEXTPROC glTexStorage1DEXT;
  PFNGLTEXSTORAGE2DEXTPROC glTexStorage2DEXT;
  PFNGLTEXSTORAGE3DEXTPROC glTexStorage3DEXT;
  PFNGLTEXSTORAGE3DMULTISAMPLEOESPROC glTexStorage3DMultisampleOES;
  PFNGLTEXSUBIMAGE3DOESPROC glTexSubImage3DOES;
  PFNGLTEXTURESTORAGE1DEXTPROC glTextureStorage1DEXT;
  PFNGLTEXTURESTORAGE2DEXTPROC glTextureStorage2DEXT;
  PFNGLTEXTURESTORAGE3DEXTPROC glTextureStorage3DEXT;
  PFNGLTEXTUREVIEWEXTPROC glTextureViewEXT;
  PFNGLTEXTUREVIEWOESPROC glTextureViewOES;
  PFNGLTRANSFORMPATHNVPROC glTransformPathNV;
  PFNGLUNIFORM1I64NVPROC glUniform1i64NV;
  PFNGLUNIFORM1I64VNVPROC glUniform1i64vNV;
  PFNGLUNIFORM1UI64NVPROC glUniform1ui64NV; 
  PFNGLUNIFORM1UI64VNVPROC glUniform1ui64vNV;
  PFNGLUNIFORM2I64NVPROC glUniform2i64NV;
  PFNGLUNIFORM2I64VNVPROC glUniform2i64vNV;
  PFNGLUNIFORM2UI64NVPROC glUniform2ui64NV;
  PFNGLUNIFORM2UI64VNVPROC glUniform2ui64vNV;
  PFNGLUNIFORM3I64NVPROC glUniform3i64NV;
  PFNGLUNIFORM3I64VNVPROC glUniform3i64vNV;
  PFNGLUNIFORM3UI64NVPROC glUniform3ui64NV;
  PFNGLUNIFORM3UI64VNVPROC glUniform3ui64vNV;
  PFNGLUNIFORM4I64NVPROC glUniform4i64NV;
  PFNGLUNIFORM4I64VNVPROC glUniform4i64vNV;
  PFNGLUNIFORM4UI64NVPROC glUniform4ui64NV;
  PFNGLUNIFORM4UI64VNVPROC glUniform4ui64vNV;
  PFNGLUNIFORMHANDLEUI64NVPROC glUniformHandleui64NV;
  PFNGLUNIFORMHANDLEUI64VNVPROC glUniformHandleui64vNV;
  PFNGLUNIFORMMATRIX2X3FVNVPROC glUniformMatrix2x3fvNV;
  PFNGLUNIFORMMATRIX2X4FVNVPROC glUniformMatrix2x4fvNV;
  PFNGLUNIFORMMATRIX3X2FVNVPROC glUniformMatrix3x2fvNV;
  PFNGLUNIFORMMATRIX3X4FVNVPROC glUniformMatrix3x4fvNV;
  PFNGLUNIFORMMATRIX4X2FVNVPROC glUniformMatrix4x2fvNV;
  PFNGLUNIFORMMATRIX4X3FVNVPROC glUniformMatrix4x3fvNV;
  PFNGLUNMAPBUFFEROESPROC glUnmapBufferOES;    // aliases glUnmapBufferARB
  PFNGLUSEPROGRAMSTAGESEXTPROC glUseProgramStagesEXT;
  PFNGLVALIDATEPROGRAMPIPELINEEXTPROC glValidateProgramPipelineEXT;
  PFNGLVERTEXATTRIBDIVISORANGLEPROC glVertexAttribDivisorAngle;
  PFNGLVERTEXATTRIBDIVISOREXTPROC glVertexAttribDivisiorEXT;
  PFNGLVERTEXATTRIBDIVISORNVPROC glVertexAttibDivisorNV;
  PFNGLVIEWPORTARRAYVNVPROC glViewportArrayvNV;
  PFNGLVIEWPORTARRAYVOESPROC glViewportArrayvOES;
  PFNGLVIEWPORTINDEXEDFNVPROC glViewportIndexedfNV;
  PFNGLVIEWPORTINDEXEDFOESPROC glViewportIndexedfOES;
  PFNGLVIEWPORTINDEXEDFVNVPROC glViewportIndexedfvNV;
  PFNGLVIEWPORTINDEXEDFVOESPROC glViewportIndexedfvOES;
  PFNGLVIEWPORTSWIZZLENVPROC glViewportSwizzleNV;
  PFNGLWAITSYNCAPPLEPROC glWaitSyncAPPLE;
  PFNGLWEIGHTPATHSNVPROC glWeightPathsNV;
  PFNGLWINDOWRECTANGLESEXTPROC glWindowRectanglesEXT;
  // --  
};
